// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8ecR4AsZc0OECL_GCA4qGnJZq9hOcxiw',
    appId: '1:329545855641:web:8bad5d2cd267381ca5fe08',
    messagingSenderId: '329545855641',
    projectId: 'feedback-app-b1ea0',
    authDomain: 'feedback-app-b1ea0.firebaseapp.com',
    storageBucket: 'feedback-app-b1ea0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtUuZHWLVI3ijYYXzdXoj41zjKX2_PdB8',
    appId: '1:329545855641:android:5d564b90ffc6e75ea5fe08',
    messagingSenderId: '329545855641',
    projectId: 'feedback-app-b1ea0',
    storageBucket: 'feedback-app-b1ea0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuEHv4WvOorhU7p7YUAEXDoc6ZYLg2kzA',
    appId: '1:329545855641:ios:cf1d0150fe7adf4aa5fe08',
    messagingSenderId: '329545855641',
    projectId: 'feedback-app-b1ea0',
    storageBucket: 'feedback-app-b1ea0.appspot.com',
    iosBundleId: 'com.example.feedbackApp',
  );
}
